//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGDatabaseEntities : DbContext
    {
        public SGDatabaseEntities()
            : base("name=SGDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Course> Course { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<StudyGroup> StudyGroup { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
    }
}
